name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:
    name: Build ➡️ Push ➡️ Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --rm=false -t masonhall/relevant-post-bot:latest
        echo ${{ secrets.DOCKER_ACCESS_KEY }} | docker login --password-stdin --username masonhall
        docker push masonhall/relevant-post-bot:latest

    - name: Pull and deploy it from server
      uses: appleboy/ssh-action@master
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        envs: CLIENT_ID,CLIENT_SECRET,REDDIT_USERNAME,REDDIT_PASSWORD
        script: |
          echo "Updating RP Bot..."
          docker pull masonhall/relevant-post-bot:latest
          docker rm -f bot
          docker run --restart always -d --name bot \
          --volume /home/ec2-user/rp_bot_posts.db:/app/src/chess_posts.db \
          --env $CLIENT_ID \
          --env $CLIENT_SECRET \
          --env USERNAME=$REDDIT_USERNAME \
          --env PASSWORD=$REDDIT_PASSWORD \
          masonhall/relevant-post-bot:latest