name: Docker Image CI

on:
  push:

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . -t masonhall/relevant-post-bot:latest
        echo ${{ secrets.DOCKER_ACCESS_KEY }} | docker login --password-stdin --username masonhall
        docker push masonhall/relevant-post-bot:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          echo "Updating RP Bot..."
          ./update.sh
